services:
  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver;Database=SubmissionDb;User Id=sa;Password=Password123!;Encrypt=False;TrustServerCertificate=True
    ports:
      - "4401:8080"
      - "4451:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/https:/home/app/.aspnet/https:ro 

  journals-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Redis=redis://journals-redisdb:6379
    ports:
      - "4402:8080"
      - "4452:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/https:/home/app/.aspnet/https:ro
  
  articleHub-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Postgres=Server=postgres;Database=ArticleHubDb;Username=postgres;Password=Password123!
    ports:
      - "4403:8080"
      - "4453:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  submission-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver;Database=SubmissionDb;Username=sa;Password=Password123!
    ports:
      - "4404:8080"
      - "4454:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/https:/home/app/.aspnet/https:ro

  review-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=sqlserver;Database=ReviewDb;Username=sa;Password=Password123!
    ports:
      - "4405:8080"
      - "4455:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro 
      - ${APPDATA}/ASP.NET/https:/home/app/.aspnet/https:ro
  
  sqlserver:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
  
  journals-redisdb:
    restart: always
    ports: 
      - "6379:6379"
      - "8801:8801" 
  
  articlehub-hasura:
    restart: always
    environment:
      - HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:Password123!@postgres:5432/ArticleHubDb
      - HASURA_GRAPHQL_ADMIN_SECRET=secret 
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
    ports:
      - "4493:8080"
      - "4494:8081"
   
  postgres:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password123!
      - POSTGRES_DB=ArticleHubDb
  
  mongo-gridfs:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password123!
    ports:
      - "27018:27017"
  
  rabbitmq:
    container_name: rabbitmq
    hostname: articles-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest